// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA414XW5htc8DbWcPikq3aPrMoBGDB_3IA',
    appId: '1:109806097168:web:b619b30844e40a1010cb95',
    messagingSenderId: '109806097168',
    projectId: 'practice-notifications-be9fe',
    authDomain: 'practice-notifications-be9fe.firebaseapp.com',
    storageBucket: 'practice-notifications-be9fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wD6i514lqERYKBXbJu0WdyTeU33qHxQ',
    appId: '1:109806097168:android:11a41c355c36325510cb95',
    messagingSenderId: '109806097168',
    projectId: 'practice-notifications-be9fe',
    storageBucket: 'practice-notifications-be9fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiMyIc9shiHTy8mnCNhvvjeOM-SYPspB0',
    appId: '1:109806097168:ios:ff1043a600169e6c10cb95',
    messagingSenderId: '109806097168',
    projectId: 'practice-notifications-be9fe',
    storageBucket: 'practice-notifications-be9fe.firebasestorage.app',
    iosBundleId: 'com.ahmed.practiceNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiMyIc9shiHTy8mnCNhvvjeOM-SYPspB0',
    appId: '1:109806097168:ios:ff1043a600169e6c10cb95',
    messagingSenderId: '109806097168',
    projectId: 'practice-notifications-be9fe',
    storageBucket: 'practice-notifications-be9fe.firebasestorage.app',
    iosBundleId: 'com.ahmed.practiceNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA414XW5htc8DbWcPikq3aPrMoBGDB_3IA',
    appId: '1:109806097168:web:fad416ed611a181c10cb95',
    messagingSenderId: '109806097168',
    projectId: 'practice-notifications-be9fe',
    authDomain: 'practice-notifications-be9fe.firebaseapp.com',
    storageBucket: 'practice-notifications-be9fe.firebasestorage.app',
  );
}
